# Generated by Django 5.0.6 on 2024-07-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='more_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
